#!/bin/busybox sh
echo ""
echo "============================================"
echo "==             G8OS INITRAMFS             =="
echo "============================================"

echo "[+] creating ram filesystem"
mount -t tmpfs tmpfs /mnt/root -o size=256M
mount -t devtmpfs devtmpfs /dev

echo "[+] building ram filesystem"
target="/mnt/root"
cp -ar /bin $target
cp -ar /etc $target
cp -ar /lib* $target
cp -ar /usr $target
cp -ar /root $target
cp -ar /bin $target
cp -ar /tmp $target
cp -ar /sbin $target
cp -ar /var $target
cp -ar /run $target

mkdir -p $target/dev
mkdir -p $target/sys
mkdir -p $target/proc
mkdir -p $target/mnt

mount -t proc proc $target/proc
mount -t sysfs sysfs $target/sys
mount -t devtmpfs devtmpfs $target/dev

mkdir -p $target/dev/pts
mount -t devpts devpts $target/dev/pts

echo "[+] setting environment"
export PATH

echo "[+] switching root"
exec switch_root /mnt/root /sbin/core0
